
= Guess a word

Implementation of "Guess a word" client and server in Rust.

== Setup

. Install Rust and Cargo. On fresh Ubuntu install this can be done by running the following commands:
+
----
sudo apt update && sudo apt upgrade && sudo apt install curl
sudo apt install build-essential
curl https://sh.rustup.rs -sSf | sh
----
+
When prompted for installation options, continue with defaults, which should look like this:
+
----
 default host triple: x86_64-unknown-linux-gnu
   default toolchain: stable (default)
             profile: default
modify PATH variable: yes
----
+
If installation went successfully, you should see the following line:
+
----
Rust is installed now. Great!
----
+
Now, restart your terminal (to make sure PATH variable is up to date).
. Navigate to the repo root (directory containing this file) in your terminal and run command below according to whether you want to run the server or a client (or both).

== Executables

=== Server

The server executable accepts connections from clients and facilitates their games with each other.

Possible arguments:

* `--server-password` (mandatory, e.g. `password`)
* `--tcp-port` (mandatory group footnote:listener[At least one listener must be selected.])
* `--unix-socket-path` (mandatory group footnote:listener[At least one listener must be selected.] footnote:unixonly[Only available on Unix systems.])

Example:

----
cargo run --release --bin server -- --server-password aaaaaaa --tcp-port 7777
----

=== Client

Client allows user to connect to the server and play a game with another user connected to the same server.

Possible arguments:

* `--tcp-address` (mandatory group footnote:destination[Exactly one target destination must be selected.])
* `--unix-socket-path` (mandatory group footnote:unixonly[] footnote:destination[])

Example: 

----
cargo run --release --bin client -- --tcp-address 127.0.0.1:7777
----

=== Tests

To run tests, run the following command:

----
cargo test
----
